# Generated by Django 3.1 on 2020-08-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200828_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cSub', to='classes.classname'),
        ),
        migrations.AlterField(
            model_name='classtopic',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cSub', to='classes.classsubject'),
        ),
    ]
