# Generated by Django 3.1 on 2020-08-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200828_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtopic',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cTop', to='classes.classsubject'),
        ),
    ]
