# Generated by Django 3.1 on 2020-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
