# Generated by Django 3.1 on 2020-08-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=200)),
                ('bookDescription', models.TextField()),
                ('bookImage', models.ImageField(upload_to='subjects/images')),
                ('bookPro', models.BooleanField(default=False, verbose_name='Pro Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFiles', models.FileField(blank=True, null=True, upload_to='subjects/Videos')),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='subjects/pdfFiles')),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
